/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day1;

import java.io.IOException;
import java.lang.Math;
import java.io.File;
import java.util.Scanner;


public class App {
    public static int fuelForMass(int mass) throws ArithmeticException {
        // fuel = (mass / 3), round down, and subtract 2
        float gas = Math.floorDiv(mass, 3) - 2;
        if ( gas > 0) {
            return (int) gas;
        } else {
            return 0;
        }
    }

    public static int fuelForFuel(int fuel) throws ArithmeticException {
        // fuel = (mass / 3), round down, and subtract 2
        int gas  = fuelForMass( fuel );
        if ( gas > 0) {
            return gas + fuelForFuel( (int) gas );
        } else {
            return 0;
        }
    }

    public static void main(String[] args) {
        int fuel = 0;
        try {
            File file = new File("/Users/afaris/work/public/advent_of_code/2019/day1/src/main/java/day1/data.txt");
            Scanner sc = new Scanner(file);

            while (sc.hasNextLine()) {
                //Fuel is solution to part 1
                //fuel = fuel + fuelForMass(sc.nextInt());

                //Fuel is solution to part 2
                fuel = fuel + fuelForFuel(sc.nextInt());
            }
        } catch (IOException e) {
            System.out.println("Unable to open file: " + e);
        }

        System.out.println("Fuel is: " + fuel);

    }
}
