/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day1;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testCalculateFuel() {
        App classUnderTest = new App();
        assertTrue(classUnderTest.fuelForMass(12) == 2 ) ;
        assertTrue(classUnderTest.fuelForMass(14) == 2 ) ;
        assertTrue(classUnderTest.fuelForMass(1969) == 654 ) ;
        assertTrue(classUnderTest.fuelForMass(100756) == 33583 ) ;
    }
}
